#!/usr/bin/python3

import binascii
import os

def analysis(bin_path: str, out_txt_path: str):
    fsize = os.path.getsize(bin_path)
    with open(bin_path, 'rb') as f:
        with open(out_txt_path, 'a+') as new_f:
            for i in range(0, fsize, 4):
            	# 二进制（bytes）类型转换成十六进制类型
                new_hew = binascii.b2a_hex(f.read(4)).decode('unicode_escape')
                # 以str格式逐行写入到文本
                print(new_hew)
                new_f.write(str(new_hew) + '\n')
        print("解析完成")


if __name__ == '__main__':
    input_file_path = "./inst_rom.bin"
    out_file_path = "./inst_rom.data"
    analysis(input_file_path, out_file_path)